version: '3'

services:
###> doctrine/doctrine-bundle ###
  web_app:
    build: .
    container_name: web-app
    depends_on:
        - db_app
    ports:
        - "80:80"
    volumes:
        - ./log:/var/log/apache2
        - ./app:/var/www/html
        - ./vhosts:/etc/apache2/sites-enabled
    networks:
        - net-app
  db_app:
    image: mariadb
    container_name: data_app
    restart: always
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=root
    ports:
        - "3306:3306"
    networks:
        - net-app
    volumes:
        - ./db:/var/lib/mysql
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

networks:
    net-app: